services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: inspire-ha
    ports:
      - "8123:8123"
    volumes:
      - ./config:/config
      - ./custom_components/inspire_home_automation:/config/custom_components/inspire_home_automation
    restart: unless-stopped
